hw_2
DoroshenkoDenis/niffler-st5 pull request #2
Opened 2024-04-30 21:33 UTC by DoroshenkoDenis

Реализована возможность использования любого числа любых пользователей. Ограничение только пререквизитами.

2024-05-07 16:08 UTC, sashkir7 requested changes
Хорошая работа, но нужно внести ряд правок
Более детально отписался в комменатриях

2024-05-07 16:08 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/extension/UserQueueExtension.java
> +            long fifteenSecondsLater = new Date().getTime() + 30000;
Название переменной - лучше использовать что-то типа endTime
(15 в названии вообще не при чем =))

2024-05-07 16:08 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/extension/UserQueueExtension.java
> +        throw new ParameterResolutionException("No more users of type " + userType + " available");
А для чего эта конструкция?
Мне кажется, что реализовали сильно сложнее, чем можно было. Еще и с обработкой мнопоточности...
По факту - мы просто должны достать мапу из стора - и вернуть (return) пользователя по ключу, который представляет из себя тип пользователя

2024-05-07 16:08 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/extension/UserQueueExtension.java
> +                .toList();
Хорошо бы добавить еще обработку BeforeEach-методов. 
Сейчас они просто игнорируются

2024-05-07 16:08 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/pages/FriendsBrowsePage.java
> +    }
Так делать не нужно
В selenide есть проверки shouldHave/shouldBe - используйте их
И возвращать boolean не нужно

2024-05-07 16:08 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/pages/FriendsBrowsePage.java
> +    }
Мало того, проверки от selenide - умные. То есть, если элемент появится через 1 секунду, то ваша проверка - упадет. А проверка от selenide пройдется итеративно - и все будет ок

2024-05-07 16:08 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/pages/FriendsBrowsePage.java
> +    }
Аналогино - используйте проверки от selenide

2024-05-07 16:08 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/pages/LoginPage.java
> +    @Step
А описание шага где? Иначе зачем он?

2024-05-07 16:08 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/pages/PeopleBrowsePage.java
> +        }
Не надо так - проверки от selenide

2024-05-07 16:08 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/pages/PeopleBrowsePage.java
> +        }
Аналогично

2024-05-07 16:08 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/pages/common/HeaderMenu.java
> +    }
И тут тоже

2024-05-07 16:08 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/test/UsersFriendsTest.java
> +    void withFiendsInvitationSendTest3(
Круто, что такой кейс тоже предусмотрели!

2024-05-07 17:25 UTC, DoroshenkoDenis commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/extension/UserQueueExtension.java
> +        throw new ParameterResolutionException("No more users of type " + userType + " available");
Я сначала и пробовал просто достать мапу из стора и вернуть (return) пользователя по ключу, который представляет из себя тип пользователя. У меня была проблема в том, что в мапе может быть два пользователя с одним типом, и достаётся всегда первый. Поэтому я решил отдельно фильтровать уже "обработанного" пользователя.

2024-05-09 02:27 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/extension/UserQueueExtension.java
> +        throw new ParameterResolutionException("No more users of type " + userType + " available");
В resolveParameter() мы не должны выполнять никакой сложной логики. Просто достали объект - и его вернули. Если мы хотим поддерживать кейс, когда есть возможность прокинуть несколько пользователей одной и той же роли, то нужно немного изменить код:
Вместо `Map<User.UserType, List<UserJson>> usersByType = new HashMap<>();` можно использовать другую структуру. Например, мапа, где в качестве ключа - параметр, а в качестве значения - пользователь.

2024-05-09 02:29 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/extension/UserQueueExtension.java
> +        throw new ParameterResolutionException("No more users of type " + userType + " available");
Тогда в resolveParameter() мы просто достанем данную мапу из стора - получим значение по параметру - и вернем его

2024-05-09 04:53 UTC, DoroshenkoDenis commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/extension/UserQueueExtension.java
> +                .toList();
Добавил поддержку ВСЕХ методов

2024-05-09 06:49 UTC, DoroshenkoDenis commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/extension/UserQueueExtension.java
> +                .toList();
Добавил фильтр по типу параметра

2024-05-09 08:15 UTC, DoroshenkoDenis commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/extension/UserQueueExtension.java
> +        throw new ParameterResolutionException("No more users of type " + userType + " available");
Про Map<Parameter, UserJson> совсем не понял как это реализовать.

2024-05-09 08:53 UTC, DoroshenkoDenis commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/extension/UserQueueExtension.java
> +        throw new ParameterResolutionException("No more users of type " + userType + " available");
Я хочу реализовать работу с тестом вида ниже. Пока ни у кого не увидел, экстеншена работающего с этим. Может есть пример? 

 @BeforeEach
    void doLogin(@User(INVITATION_SEND) UserJson sender, @User(WITH_FRIENDS) UserJson friend) {
        Selenide.open("http://127.0.0.1:3000");
        welcomePage.goToLogin();
        loginPage.login(
                sender.username(),
                sender.testData().password());
    }

    //**************** INVITATION SEND ********************//

    @Test
    void invitationSendTest(@User(INVITATION_RECEIVED) UserJson receiver_1,
                             @User(INVITATION_RECEIVED) UserJson receiver_2) {

        assertTrue(menu.isPageLoaded(), "Бро, я не вижу аватар");

        menu.openPeopleList();

        Allure.step("Проверка: Pending invitation", () -> {
            assertTrue(people.checkRowWithStatus("Pending invitation"),
                    "Бро, пора бы пригласить кого-нибудь");
        });
    }

2024-05-09 09:24 UTC, DoroshenkoDenis commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/extension/UserQueueExtension.java
> +        throw new ParameterResolutionException("No more users of type " + userType + " available");
долго догонял, как бы теперь запомнить это всё)

2024-05-12 00:37 UTC, sashkir7 approved these changes

2024-05-12 00:37 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/test/UsersFriendsBeforeMethodTest.java
> +        menu.getLogout().click();
Всю логику обращения с веб-элементами хорошо бы прятать в page-object класс
То есть, чтобы тестовый класс вообще ничего не знал про SelenideElement

2024-05-12 00:37 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/test/UsersFriendsBeforeMethodTest.java
> +        menu.getAvatar().should(exist);
И тут тоже

2024-05-29 05:10 UTC, merged